In [3]:
import numpy as np

In [4]:
np.__version__

'1.12.0'

In [5]:
1

1

In [6]:
L = [1,2,3]
L[::-1]

[3, 2, 1]

In [8]:
np.linspace(0,1,12,endpoint=True)

array([ 0.        ,  0.09090909,  0.18181818,  0.27272727,  0.36363636,
        0.45454545,  0.54545455,  0.63636364,  0.72727273,  0.81818182,
        0.90909091,  1.        ])

In [9]:
A = np.random.randint(0,10,(3,4,3,4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print(sum)

[[59 41 77 68]
 [65 56 38 69]
 [53 68 46 48]]


In [10]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[ 1.  0.  0.  0.  2.  0.  0.  0.  3.  0.  0.  0.  4.  0.  0.  0.  5.]


In [12]:
array = [1,2,3,6,5,4]
for i in range(len(array)):
    for j in range(i):
        if array[j] > array[j + 1]:
            array[j], array[j + 1] = array[j + 1], array[j]
array

[1, 2, 3, 5, 4, 6]

In [13]:
def bubblesort(numbers):
    for j in range(len(numbers)-1,-1,-1):
        for i in range(j):
            if numbers[i]>numbers[i+1]:
                numbers[i],numbers[i+1] = numbers[i+1],numbers[i]
            print(i,j)
            print(numbers)

In [14]:
bubblesort(array)

0 5
[1, 2, 3, 5, 4, 6]
1 5
[1, 2, 3, 5, 4, 6]
2 5
[1, 2, 3, 5, 4, 6]
3 5
[1, 2, 3, 4, 5, 6]
4 5
[1, 2, 3, 4, 5, 6]
0 4
[1, 2, 3, 4, 5, 6]
1 4
[1, 2, 3, 4, 5, 6]
2 4
[1, 2, 3, 4, 5, 6]
3 4
[1, 2, 3, 4, 5, 6]
0 3
[1, 2, 3, 4, 5, 6]
1 3
[1, 2, 3, 4, 5, 6]
2 3
[1, 2, 3, 4, 5, 6]
0 2
[1, 2, 3, 4, 5, 6]
1 2
[1, 2, 3, 4, 5, 6]
0 1
[1, 2, 3, 4, 5, 6]


In [15]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [19]:
a = np.random.randn(30,30)

In [20]:
a.mean()

0.038239248889556252

In [21]:
a = np.arange(10)

In [22]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [32]:
x = np.random.rand(5, 10)
x

array([[ 0.33850567,  0.21601866,  0.7771187 ,  0.89953107,  0.02436305,
         0.87576841,  0.86470457,  0.44111756,  0.39810983,  0.95612765],
       [ 0.74745982,  0.78009117,  0.20074047,  0.80577955,  0.43222214,
         0.64993431,  0.77398426,  0.87324906,  0.71932536,  0.37989756],
       [ 0.91803676,  0.9740342 ,  0.26053826,  0.44031412,  0.64365713,
         0.87607809,  0.45089023,  0.73277173,  0.72813373,  0.03872222],
       [ 0.10988237,  0.4593062 ,  0.63223688,  0.22768427,  0.28641894,
         0.28132089,  0.90183483,  0.33782405,  0.33223441,  0.44757581],
       [ 0.20588929,  0.71253455,  0.42365137,  0.5952425 ,  0.19683412,
         0.10440447,  0.37526453,  0.55252609,  0.99080351,  0.09556539]])

In [33]:
Y = X - X.mean(axis=1)

In [34]:
Y

array([[ 0.24867888,  0.33786911,  0.06286186, -0.40563304, -0.52425842,
         0.22848197,  0.070174  ,  0.1085689 , -0.52343752,  0.39669425],
       [ 0.24915373,  0.02023597, -0.50566828, -0.10551387,  0.29381076,
         0.31432562, -0.08331936,  0.23843497, -0.24538206, -0.17607748],
       [-0.51834759, -0.20340376,  0.05267618,  0.31825951,  0.11665916,
        -0.20764961,  0.31096559,  0.3624026 , -0.1651663 , -0.06639577],
       [-0.19008032, -0.30450933,  0.45479945, -0.09075594,  0.12959771,
        -0.23735478, -0.08608037, -0.01722733,  0.40048558, -0.05887468],
       [ 0.34057855,  0.26223427,  0.34167045, -0.22810676, -0.12385926,
        -0.40838902,  0.27184048,  0.31381074, -0.41818721, -0.35159225]])

In [36]:
Y = X - X.mean(axis=1).reshape(-1, 1)

In [37]:
Y

array([[ 0.24867888,  0.33786911,  0.06286186, -0.40563304, -0.52425842,
         0.22848197,  0.070174  ,  0.1085689 , -0.52343752,  0.39669425],
       [ 0.24915373,  0.02023597, -0.50566828, -0.10551387,  0.29381076,
         0.31432562, -0.08331936,  0.23843497, -0.24538206, -0.17607748],
       [-0.51834759, -0.20340376,  0.05267618,  0.31825951,  0.11665916,
        -0.20764961,  0.31096559,  0.3624026 , -0.1651663 , -0.06639577],
       [-0.19008032, -0.30450933,  0.45479945, -0.09075594,  0.12959771,
        -0.23735478, -0.08608037, -0.01722733,  0.40048558, -0.05887468],
       [ 0.34057855,  0.26223427,  0.34167045, -0.22810676, -0.12385926,
        -0.40838902,  0.27184048,  0.31381074, -0.41818721, -0.35159225]])

In [38]:
Z = np.dot(np.random.random((5,3)), np.random.random((3,2)))
print(Z)

[[ 0.33287548  0.69007339]
 [ 0.53992368  0.97965634]
 [ 0.44767046  0.72025653]
 [ 0.73600588  1.00987555]
 [ 0.77230622  1.12810392]]


In [40]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
I

array([  0,   1,   2,   3,  15,  16,  32,  64, 128])

In [41]:
A = I.reshape(-1,1)
A

array([[  0],
       [  1],
       [  2],
       [  3],
       [ 15],
       [ 16],
       [ 32],
       [ 64],
       [128]])

In [43]:
B = 2**np.arange(8)
B

array([  1,   2,   4,   8,  16,  32,  64, 128])

In [45]:
(A & B)!=0

array([[False, False, False, False, False, False, False, False],
       [ True, False, False, False, False, False, False, False],
       [False,  True, False, False, False, False, False, False],
       [ True,  True, False, False, False, False, False, False],
       [ True,  True,  True,  True, False, False, False, False],
       [False, False, False, False,  True, False, False, False],
       [False, False, False, False, False,  True, False, False],
       [False, False, False, False, False, False,  True, False],
       [False, False, False, False, False, False, False,  True]], dtype=bool)

In [ ]:
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

In [46]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1).reshape(-1, 1)

In [47]:
Y

array([[ 0.41249613, -0.54064358,  0.26433082,  0.19839639, -0.23457482,
         0.16148717, -0.02071315,  0.38255338, -0.22351795, -0.39981439],
       [-0.00166576, -0.2374005 , -0.34677819,  0.36584572,  0.22959242,
        -0.34437947, -0.21390163,  0.51409251,  0.16011043, -0.12551553],
       [-0.03328057, -0.22828419, -0.29474377, -0.29876002,  0.3403778 ,
        -0.06895611,  0.1726515 ,  0.42879248,  0.32796694, -0.34576407],
       [ 0.04105634,  0.28177886, -0.36259901,  0.12978063, -0.40619318,
        -0.00722681,  0.25164857, -0.13174364,  0.24112099, -0.03762275],
       [ 0.08509481,  0.11811506,  0.16255209, -0.05817579,  0.1383846 ,
        -0.04376009, -0.05170441,  0.32221005, -0.35952939, -0.31318693]])

In [48]:
X.mean(axis=1).reshape(-1, 1)

array([[ 0.5476757 ],
       [ 0.37881819],
       [ 0.35642452],
       [ 0.48971847],
       [ 0.50098184]])

In [49]:
X

array([[ 0.96017184,  0.00703213,  0.81200653,  0.74607209,  0.31310088,
         0.70916288,  0.52696255,  0.93022908,  0.32415775,  0.14786131],
       [ 0.37715243,  0.14141769,  0.03203999,  0.74466391,  0.60841061,
         0.03443872,  0.16491656,  0.8929107 ,  0.53892861,  0.25330266],
       [ 0.32314395,  0.12814033,  0.06168076,  0.05766451,  0.69680233,
         0.28746842,  0.52907602,  0.78521701,  0.68439146,  0.01066046],
       [ 0.53077481,  0.77149733,  0.12711946,  0.6194991 ,  0.08352529,
         0.48249166,  0.74136704,  0.35797483,  0.73083946,  0.45209573],
       [ 0.58607665,  0.6190969 ,  0.66353393,  0.44280605,  0.63936644,
         0.45722175,  0.44927743,  0.82319189,  0.14145245,  0.18779492]])

In [51]:
np.eye(4,5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.]])

In [ ]:
z = np.random.randint(0,10,(5,5))
z

In [32]:
import numpy as np
Z = np.random.randint(0,10,(5,5))
print(Z)
print(Z[Z[:,3].argsort()])
Z[:,3].argsort()

[[6 8 8 1 9]
 [3 2 1 3 2]
 [1 7 0 7 4]
 [5 9 2 0 2]
 [6 1 5 5 1]]
[[5 9 2 0 2]
 [6 8 8 1 9]
 [3 2 1 3 2]
 [6 1 5 5 1]
 [1 7 0 7 4]]


array([3, 0, 1, 4, 2])

In [33]:
Z

array([[6, 8, 8, 1, 9],
       [3, 2, 1, 3, 2],
       [1, 7, 0, 7, 4],
       [5, 9, 2, 0, 2],
       [6, 1, 5, 5, 1]])

In [34]:
Z[3]

array([5, 9, 2, 0, 2])

In [35]:
Z[[3]]

array([[5, 9, 2, 0, 2]])

In [36]:
Z[3,4]

2

In [37]:
Z[3,4]
Z

array([[6, 2, 8, 1, 9],
       [3, 2, 1, 3, 2],
       [1, 7, 0, 7, 4],
       [5, 9, 2, 0, 2],
       [6, 1, 5, 5, 1]])

In [18]:
Z

array([[1, 0, 6, 4, 9],
       [1, 0, 6, 4, 9],
       [9, 3, 8, 4, 0],
       [1, 5, 7, 8, 7],
       [2, 4, 7, 0, 3]])

In [17]:
Z
tmp=Z[0].copy()
Z[0]=Z[1].copy()
Z[1]=tmp
Z

array([[1, 0, 6, 4, 9],
       [1, 0, 6, 4, 9],
       [9, 3, 8, 4, 0],
       [1, 5, 7, 8, 7],
       [2, 4, 7, 0, 3]])

In [56]:
x = np.array([1,2,3,4])
print(x)
print(type(x[0]))
x[0],x[1]=x[1],x[0]
print(x)

[1 2 3 4]
<class 'numpy.int64'>
[2 1 3 4]


In [57]:
Z = np.random.randint(0,10,(5,5))
print(Z)
print(type(Z[0]))
Z[0],Z[1]=Z[1],Z[0]
print(Z)

[[2 7 6 7 4]
 [3 2 0 4 0]
 [9 3 0 4 5]
 [6 1 2 1 3]
 [3 8 0 6 7]]
<class 'numpy.ndarray'>
[[3 2 0 4 0]
 [3 2 0 4 0]
 [9 3 0 4 5]
 [6 1 2 1 3]
 [3 8 0 6 7]]


In [58]:
Z = np.random.randint(0,10,(5,5))
print(Z)
tmp = Z[0].copy()
Z[0]=Z[1]
Z[1]=tmp
print(Z)

[[3 1 4 8 8]
 [5 7 7 3 3]
 [2 4 7 9 4]
 [5 6 0 4 5]
 [6 9 1 5 7]]
[[5 7 7 3 3]
 [3 1 4 8 8]
 [2 4 7 9 4]
 [5 6 0 4 5]
 [6 9 1 5 7]]
